name: Maven CI/CD

on:
 push:
    branches: [ main ]

jobs:
  build:
    
    name: Build Image
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: Check out code
      uses: actions/checkout@v2
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 #region

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: xgileit #repository name
        IMAGE_TAG: latest #tag
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
    
    - name: Deploy to Kubernetes cluster                                                                            
      uses: azure/setup-kubectl@v3
      with:
       version: latest # default is latest stable
      id: install	  
    
    - name : update config
      run : aws eks --region us-east-2 update-kubeconfig --name test_cluster
    
    - name : Deploy to EKS
      run: |  
        kubectl apply -f aws/deployments/deployment.yaml
        kubectl apply -f aws/deployments/service.yaml
